name: 'PMD Node16'
author: Felipe Echanique Torres
description: 'This action allows to use PMD Source Code Analyzer from GitHub Actions'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'award'  
  color: 'red'
